### ISSUE TITLE
Metrics: Page

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse.org#6]
Need to determine:
- [x] what metrics will be in the card on the homepage
- [x] what metrics will be on the By the Numbers page
- [ ] display an interesting dataset or dataverse
- [x] do you want to add dynamic numbers from the 3.6 homepage: http://thedata.harvard.edu/dvn/?
    e.g. pull these numbers 1x to Nx per day.

**Comment by pdurbin** [comment]
We just redid https://dataverse.org/metrics to show metrics for 12 Dataverse installations around the world rather than just Harvard Dataverse. This ancient ticket didn't come up. If anyone has any suggestions, please open a new issue in this new repo: https://github.com/IQSS/dataverse-metrics

Closing.
