### ISSUE TITLE
Confusion with Best Practices pages being hosted on OpenScholar and github/Sphinx

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse.org#62]
Two versions of the Best Practices pages are publicly accessible from dataverse.org:

1. On http://best-practices.dataverse.org/, which is hosted on github and generated with sphinx
2. And on the pages here: https://dataverse.org/best-practices/academic-credit, hosted on OpenScholar

So two versions of pages like the Harvard Dataverse Terms of Use are on [github](https://github.com/IQSS/dataverse.org/blob/master/docs/best_practices/source/harvard-policies/harvard-terms-of-use.rst) and [on OpenScholar](https://dataverse.org/best-practices/harvard-dataverse-general-terms-use), and people can and do navigate to both pages, and find both pages through google searches. (They both get about the same amount of web traffic.) This can complicate navigation around those guides and confuse users when google sends them to versions of the same text that look different.

We have the pages on github so that Dataverse installations can take and revise them, e.g.:
- http://www.library.virginia.edu/libra/datasets/libra-data-community-norms/
- http://data.tdl.org/policies/#community-norms

How do we make sure there is only one public version of the Best Practices pages?

- Can we have the pages hosted on github be the only version, remove (or at least hide at first) the copies on OpenScholar, and link the github/sphinx versions on the navigation bar on the OpenScholar site? I don't think that would be difficult to do technically.
  - If we do this, we'll just have to make sure we have all of the content and it's the most updated. We could do that section by section, starting with the Harvard Dataverse Policies pages, which contain the pages Harvard lawyers are helping us update now as part of the security changes (general terms of use and possibly API terms of use).
  - If we do this, we should look into styling the sphinx pages so they look like the other OpenScholar pages? (breadcrumbs, same font face, left navigation column, etc.) 

- If we shouldn't or can't do that, can we remove the sphinx Best Practices pages (but keep the pages on github) and make sure we keep both the text in github and on OpenScholar in sync?
  - Is it a matter of setting up a process to remind ourselves to change one version when the other is changed? There are minor changes right now between the General Terms of Use in github and the General Terms of Use on OpenScholar (and the General Terms of Use in the database, which is what's being shown to users on Harvard Dataverse's create account page).
  - Or is there a way to keep any or all of these versions in sync programmatically?

**Comment by jggautier** [comment]
I think this issue is related to the idea of separating Harvard Dataverse-specific content from Dataverse.org, since some of these best practices pages are Harvard Dataverse specific and some are more general.

**Comment by dlmurphy** [comment]
On Friday I made some minor changes to dataverse.org to improve the information architecture of the "Best Practices" pages and fix this duplicated content problem.

Here's what I did:

-Replaced all links to content on best-practices.dataverse.org (the github/sphinx pages) with links to the equivalent pages on dataverse.org (on openscholar).

-Created a Data Citation page on dataverse.org in order to bring the content from best-practices.dataverse.org into the main site. This was done in the past with all other duplicate pages except for this one. I assume this was an oversight at the time. After creating this page, I added it to the header under Best Practices and added it to the Best Practices sidebar.

-The "Dataverse Community Norms" page was linked in the Best Practices sidebar but not the header. I added it to the header to match all other Best Practices pages.

-The Best Practices sidebar was messy and confusing. I fixed it up so the hierarchy of pages is more clear, and it's easier to tell what page you're currently on.

--

As of now, there are no links to the best-practices.dataverse.org sphinx pages on dataverse.org. Julian pointed out that those sphinx pages are sometimes referenced by dataverse itself though - in the terms of use when creating an account, for example. It looks like we could edit a value in the database so that those terms link to the dataverse.org page instead. 

For now I'm not going to alter or delete the best-practices.dataverse.org sphinx pages until we are sure that we've replaced all links to it in the Dataverse application. Once we've done that, it might be a good idea to add a banner to all of those pages saying that they're out of date and linking to their equivalent pages on dataverse.org.

**Comment by dlmurphy** [comment]
Right now the last thing that needs to be done for this issue is remove duplicate content from the Dataverse application itself.

**To-do Checklist**
- [Replace all links to best-practices.dataverse.org with links to their equivalent pages on dataverse.org]

- [ Add a note to the top of each best-practices.dataverse.org page directing users to the officially maintained version of that page at dataverse.org]

**Comment by dlmurphy** [comment]
Everything that needs to be done on dataverse.org is done. Keep an eye on #4544 in the Dataverse github, where we're taking care of the links to duplicate content in the Dataverse application. Closing this issue.
