### ISSUE TITLE
Update list of features

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse.org#65]
Dataverse 4.12 was just released but our features page is really out of date:

<img width="1308" alt="Screen Shot 2019-04-07 at 9 10 11 PM" src="https://user-images.githubusercontent.com/21006/55692851-98bdc800-5979-11e9-8c91-9cc368f3ec6e.png">

Last updated 3.5 years ago:

<img width="1358" alt="Screen Shot 2019-04-07 at 9 11 50 PM" src="https://user-images.githubusercontent.com/21006/55692892-d6225580-5979-11e9-9602-a0031967cfd9.png">

Obvious ones to add:

- Dropbox integration
- OAuth login (ORCID, GitHub, Google)
- Widgets
- OAI-PMH
- Make Data Count

I was telling @jggautier last week that we should crowdsource this a bit. I'll probably ask the community for their favorite features. Plus, we should compare against our Comparative Review of Various Data Repositories at https://dataverse.org/blog/comparative-review-various-data-repositories

**Comment by pdurbin** [comment]
In this "favorite features of Dataverse?" thread, I'm asking the community for their thoughts: https://groups.google.com/d/msg/dataverse-community/cy6Jc0oZ-wM/1fkwgfaaAgAJ

**Comment by pdurbin** [comment]
I'm very happy to see that @ross-spencer is spreading the word! Check out this tweet: https://twitter.com/beet_keeper/status/1115140899611250688

<img width="594" alt="Screen Shot 2019-04-08 at 9 06 17 AM" src="https://user-images.githubusercontent.com/21006/55726403-b886d780-59dd-11e9-98ab-4eb29a1a045c.png">

**Comment by ghost** [comment]
When it comes to data management software, Dataverse addressed two of our key requirements:

1. The need for a strong PIUD, and Dataverse offers this with DOIs and Handles. We see this as a major incentive for researchers to deposit their data and get more value out of their data collections, instead of just the publications based upon them. (I think this aspect is partially covered by the first point in the list, support for FAIR Data Principles, but the added value of the DOI — its popularity among researchers and bibliographic database crawlers — is a huge bonus.)

2. The ability to automatically generate DDI. DDI is the number one standard for social science metadata, and it is one of the main requirements of the Consortium of European Social Science Data Archives (CESSDA). Besides Nesstar (free but no longer supported) and Colectica (commercial), there aren't many other programs around that offer this possibility.

**Comment by pdurbin** [comment]
I updated the features list back in 2019 so I'm closing this issue. Here's how the page looks.

![Screenshot 2022-02-15 at 14-15-02 Features](https://user-images.githubusercontent.com/21006/154133675-eec7852f-f1c8-4586-9a0b-8f6eab6d8dd4.png)

Now's it's 2022 and probably time to update it again at some point. Here's a new issue for that: https://github.com/IQSS/dataverse/issues/8426

@BPeuch and anyone else reading this, please feel free to follow along and contribute! Not sure when we'll do this though. 😄

**Comment by ghost** [comment]
Looks great, @pdurbin!

I think you could add the metadata customization feature. That was also definitely a big +1 for us when we were on the lookout for a collection management Web application :)
